'use strict';
const assert = require('node:assert/strict');
const puppeteer = require('puppeteer');
const { installPageInline } = require('./inline.cjs');
const { installReviewUI } = require('./review-ui.cjs');
(async () => {
  const browser = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
  try {
    const page = await browser.newPage();
    const requests = [], lookups = [];
    const memoryRequests = []; const opened=[];
    await page.exposeFunction('onOpenRecord',url=>{opened.push(url);return true;});
    const actions = [];
    let connections = 0;
    await page.exposeFunction('onSeraConnect', () => { connections++; });
    await page.exposeFunction('onSeraSend', id => { memoryRequests.push(id); });
    await page.exposeFunction('onSeraAction', (id, action, values) => { actions.push({ id, action, values }); });
    await page.exposeFunction('onVoiceTranscribe', id => { requests.push(id); });
    await page.exposeFunction('onVoiceLookup', ids => { lookups.push(...ids); });
    await page.setContent('<div data-id="voice"></div><div data-id="sent"></div><div data-id="text"></div>');
    await page.evaluate(() => {
      const records = { voice: { type: 'ptt', id: { fromMe: false, id: 'domvoice' } }, sent: { type: 'ptt', id: { fromMe: true } }, text: { type: 'chat', id: {} } };
      window.require = () => ({ Msg: { get: id => records[id], getModelsArray: () => Object.values(records) } });
      window.WWebJS = { getMessageModel: msg => ({ id: { _serialized: msg === records.voice ? 'voice' : msg === records.sent ? 'sent' : undefined } }) };
      Object.defineProperty(navigator, 'clipboard', { value: { writeText: async text => { window.copiedTranscript = text; } } });
    });
    await page.evaluate(installReviewUI);
    await page.evaluate(installPageInline);
    await page.evaluate(installReviewUI);
    await page.evaluate(installPageInline);
    await page.waitForFunction(() => !!document.querySelector('.voice-transcriber button'));
    assert.equal(await page.$$eval('.voice-transcriber', elements => elements.length), 2);
    await page.click('[data-voice-message=sent] button');
    assert.deepEqual(requests, ['sent']); requests.length=0;
    await page.click('.voice-transcriber button');
    await page.waitForFunction(() => document.querySelector('.voice-transcriber button').disabled);
    assert.deepEqual(requests, ['voice']);
    assert.deepEqual(lookups, ['voice','sent']);
    const transcript = '<img src=x onerror=alert(1)> A local transcript.';
    await page.evaluate(transcript => window.VoiceTranscriber.update([{ id: 'voice', status: 'done', transcript }]), transcript);
    assert.equal(await page.$eval('.voice-transcriber p', element => element.textContent), transcript);
    assert.equal(await page.$eval('.voice-transcriber', e => e.dataset.state), 'transcribed');
    assert.equal(await page.$$eval('.voice-transcriber img', elements => elements.length), 0);
    await page.click('.voice-transcriber button');
    assert.equal(await page.evaluate(() => window.copiedTranscript), transcript);
    await page.evaluate(() => { navigator.clipboard.writeText = async () => { throw Error('Clipboard blocked'); }; });
    await page.click('.voice-transcriber button');
    assert.equal(await page.$eval('.voice-transcriber button', el => el.textContent), 'Copy unavailable');
    assert.equal(await page.$eval('.voice-transcriber p', el => el.textContent), transcript);
    await page.click('.voice-transcriber button:nth-of-type(2)');
    assert.equal(connections, 1);
    await page.evaluate(transcript => window.VoiceTranscriber.update([{ id: 'voice', status: 'done', transcript, memory: { status: 'ready' } }]), transcript);
    await page.click('.voice-transcriber button:nth-of-type(2)');
    assert.deepEqual(memoryRequests, []);
    assert.equal(await page.$$eval('dialog', els => els.length), 1);
    await page.click('[aria-label="Close review"]');
    assert.equal(await page.$$eval('dialog', els => els.length), 0);
    assert.equal(actions[0].action, 'prepare');
    actions.length = 0;
    await page.evaluate(transcript => window.VoiceTranscriber.update([{ id: 'voice', status: 'done', transcript, memory: { status: 'done', url: 'https://www.notion.so/test', advice: '<img src=x> Review the proposal.' } }]), transcript);
    assert.equal(await page.$eval('.voice-transcriber button:nth-of-type(2)', el => el.disabled), false);
    assert.equal(await page.$eval('.voice-transcriber a', el => el.href), 'https://www.notion.so/test');
    assert.equal(await page.$$eval('.voice-transcriber img', elements => elements.length), 0);
    await page.evaluate(transcript => window.VoiceTranscriber.update([{ id: 'voice', status: 'done', transcript, memory: { status: 'done', content_state: 'source_only', url: 'https://www.notion.so/original', advice: 'Existing breakdown' } }]), transcript);
    assert.equal(await page.$eval('.voice-transcriber button:nth-of-type(2)', el => el.textContent), 'Save Sera breakdown');
    await page.click('.voice-transcriber button:nth-of-type(2)');
    assert.deepEqual(memoryRequests, []);
    const draft = { title: 'Weekly rhythm proposal', transcript, summary: 'Proposal, not a decision.',
      claims: [{ text: '<img src=x> Meet Monday', kind: 'Speaker claim', evidence: 'Meet Monday' }],
      actions: [{ title: 'Prepare agenda', evidence: 'Suggestion' }], owners: [{ id: 'owner', name: 'Test owner' }, { id: 'other', name: 'Other owner' }],
      related: [{ id: 'topic', title: 'Topic history', url: 'https://www.notion.so/topic' }], selected_related: ['topic'], tasks: [], verified: false };
    await page.evaluate(({ transcript, draft }) => window.VoiceTranscriber.update([{ id: 'voice', status: 'done', transcript, memory: { status: 'ready', draft } }]), { transcript, draft });
    assert.equal(await page.$$eval('dialog .vr-scroll img', els => els.length), 0);
    await page.$eval('dialog input[aria-label="Memory title"]', el => { el.value = 'Edited KB title'; });
    await page.$$eval('dialog button', bs => bs.find(b => b.textContent === 'Publish memory').click());
    const published = actions.find(a => a.action === 'publish');
    assert.equal(published.values.title, 'Edited KB title'); assert.deepEqual(published.values.related_ids, ['topic']);
    draft.verified = true; draft.url = 'https://www.notion.so/published';
    await page.evaluate(({ transcript, draft }) => window.VoiceTranscriber.update([{ id: 'voice', status: 'done', transcript, memory: { status: 'done', draft } }]), { transcript, draft });
    assert.equal(await page.$eval('.voice-transcriber', e => e.dataset.state), 'saved');
    await page.$eval('.voice-transcriber a',e=>e.click());
    for(let i=0;i<20 && !opened.length;i++) await new Promise(resolve=>setTimeout(resolve,20));
    assert.equal(opened.length,1);
    assert.equal((await browser.pages()).length,2);
    await page.evaluate(({ transcript, draft }) => window.VoiceTranscriber.update([{ id: 'voice', status: 'done', transcript, memory: { status: 'review_error', draft, error:'Could not create task' } }]), { transcript, draft });
    assert.equal(await page.$eval('.voice-transcriber', e => e.dataset.state), 'attention');
    await page.evaluate(({ transcript, draft }) => window.VoiceTranscriber.update([{ id: 'voice', status: 'done', transcript, memory: { status: 'done', draft } }]), { transcript, draft });
    await page.click('dialog [data-task]');
    await page.type('dialog input[type=search]', 'Test');
    assert.equal(await page.$$eval('dialog .vr-person:not([hidden])', es => es.length), 1);
    await page.click('dialog [data-owner=owner]');
    await page.$eval('dialog input[type=search]', e => {e.value='';e.dispatchEvent(new Event('input'));});
    await page.click('dialog [data-owner=other]');
    await page.$eval('dialog input[type=date]', el => { el.value = '2026-10-10'; el.dispatchEvent(new Event('input')); });
    await page.$$eval('dialog button', buttons => buttons.find(b => b.textContent === 'Create shared tasks').click());
    await page.waitForFunction(() => true);
    const tasked = actions.find(a => a.action === 'tasks');
    assert.deepEqual(tasked.values.selection, [{ index: 0, owner_ids: ['other', 'owner'], due_date: '2026-10-10' }]);
    await page.$eval('dialog .vr-scroll', el => { el.scrollTop = el.scrollHeight; });
    const closeVisible = await page.$eval('[aria-label="Close review"]', el => { const r = el.getBoundingClientRect(); return r.top >= 0 && r.bottom <= innerHeight; });
    assert.equal(closeVisible, true);
    await page.click('[aria-label="Close review"]');
    assert.equal(await page.$$eval('dialog', els => els.length), 0);
    await page.click('.voice-transcriber button:nth-of-type(2)');
    await page.keyboard.press('Escape');
    assert.equal(await page.$$eval('dialog', els => els.length), 0);
    await page.evaluate(transcript => window.VoiceTranscriber.update([{ id: 'voice', status: 'done', transcript, memory: { status: 'done', content_state: 'complete', url: 'https://www.notion.so/original', analysis_url: 'https://www.notion.so/analysis', advice: 'Existing breakdown' } }]), transcript);
    assert.equal(await page.$$eval('.voice-transcriber a', elements => elements.length), 2);
    assert.equal(await page.$eval('.voice-transcriber button:nth-of-type(2)', el => el.disabled), false);
    await page.evaluate(() => {
      const replacement = document.createElement('div'); replacement.dataset.id = 'domvoice';
      document.querySelector('[data-id="voice"]').replaceWith(replacement);
    });
    await page.waitForFunction(() => document.querySelector('.voice-transcriber p'));
    assert.equal(await page.$$eval('.voice-transcriber', elements => elements.length), 2);
    assert.deepEqual(requests, ['voice']);
    await page.evaluate(() => { document.querySelector('[data-id="domvoice"]').dataset.id = 'text'; });
    await page.waitForFunction(() => !document.querySelector('[data-id=text] .voice-transcriber'));
    console.log('PASS: received and sent transcription, safe text, review/edit/publish controls, topic selection, assigned follow-ups, and reused bubbles.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
